import 'package:hive/hive.dart';
part 'note.g.dart';

@HiveType(typeId: 1) // WICHTIG: typeId NICHT ändern (liest alte Daten)!
class Note {
  @HiveField(0)
  final String id;
  @HiveField(1)
  final String title;
  @HiveField(2)
  final String body;
  @HiveField(3)
  final List<String> tags;
  @HiveField(4)
  final bool isPinned;
  @HiveField(5)
  final DateTime? remindAt;
  @HiveField(6)
  final String? imagePath;
  @HiveField(7)
  final DateTime createdAt;
  @HiveField(8)
  final DateTime updatedAt;

  const Note({
    required this.id,
    required this.title,
    required this.body,
    required this.tags,
    required this.isPinned,
    required this.remindAt,
    required this.imagePath,
    required this.createdAt,
    required this.updatedAt,
  });

  Note copyWith({
    String? id,
    String? title,
    String? body,
    List<String>? tags,
    bool? isPinned,
    DateTime? remindAt,
    String? imagePath,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return Note(
      id: id ?? this.id,
      title: title ?? this.title,
      body: body ?? this.body,
      tags: tags ?? this.tags,
      isPinned: isPinned ?? this.isPinned,
      remindAt: remindAt ?? this.remindAt,
      imagePath: imagePath ?? this.imagePath,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }
}

// NoteAdapter is generated by hive_generator (note.g.dart).
